# Generated by Django 5.2.6 on 2025-10-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='categories',
        ),
    ]
