# Generated by Django 5.2.6 on 2025-10-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archive', 'Archive')], max_length=20),
        ),
    ]
