# Generated by Django 5.2.6 on 2025-10-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
