# Generated by Django 5.2.6 on 2025-11-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_movementlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='quantity_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movementlog',
            name='quantity_before',
            field=models.IntegerField(default=0),
        ),
    ]
